
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ""

proxy-providers:
  白嫖机场:
    type: http
    url: https://x.nsa.cc/api/v1/client/subscribe?token=888fa1629a70b5492ba21d17b1f14177
    interval: 86400  # 每24小时自动更新订阅
    path: ./baipiao.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.google.com/generate_204

  节点管理系统:
    type: http
    url: https://wvw.guanxi.cloudns.be/api/v1/client/subscribe/token=9e48312624d64c219f8e7u9af55b4k238bh7
    interval: 86400  # 每24小时自动更新订阅
    path: ./guanxi.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.google.com/generate_204

  嘎嘎机场:
    type: http
    url: https://1.bethebest.eu.org/api/v1/client/subscribe?token=3715a07dc448ad9f275aa73e54b762b7
    interval: 86400  # 每24小时自动更新订阅
    path: ./gaga.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.google.com/generate_204

  马铃薯机场:
    type: http
    url: https://mlshu.com/api/v1/client/subscribe?token=4cabd6f21f4ae9dda02f1be1753f0fdb
    interval: 86400  # 每24小时自动更新订阅
    path: ./malingshu.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.google.com/generate_204

  年前机场:
    type: http
    url: https://board.nsde.date/api/v1/client/subscribe?token=84e28dd2b42173a927d7e39896350cdd
    interval: 86400  # 每24小时自动更新订阅
    path: ./nianqian.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.google.com/generate_204

  三分机场:
    type: http
    url: http://59.80.54.192:10601/api/v1/client/subscribe?token=dca03805d3639f55ce00df0858c6cee5&flag=clash
    interval: 86400  # 每24小时自动更新订阅
    path: ./sanfen.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.google.com/generate_204

proxy-groups:
  - name: "节点选择"
    type: select
    proxies:
      - 自动选择
      - 手动切换
      - 负载均衡
      - 故障转移
      - 白嫖机场
      - 节点管理系统
      - 嘎嘎机场
      - 马铃薯机场
      - 年前机场
      - 三分机场

  - name: "自动选择"
    type: url-test
    use:
      - 白嫖机场
      - 节点管理系统
      - 嘎嘎机场
      - 马铃薯机场
      - 年前机场
      - 三分机场
    url: http://www.google.com/generate_204
    interval: 300

  - name: "手动切换"
    type: select
    use:
      - 白嫖机场
      - 节点管理系统
      - 嘎嘎机场
      - 马铃薯机场
      - 年前机场
      - 三分机场

  - name: "负载均衡"
    type: load-balance
    use:
      - 白嫖机场
      - 节点管理系统
      - 嘎嘎机场
      - 马铃薯机场
      - 年前机场
      - 三分机场

  - name: "故障转移"
    type: fallback
    use:
      - 白嫖机场
      - 节点管理系统
      - 嘎嘎机场
      - 马铃薯机场
      - 年前机场
      - 三分机场

  # 为每个机场单独创建一个策略组
  - name: "白嫖机场"
    type: select
    use:
      - 白嫖机场

  - name: "节点管理系统"
    type: select
    use:
      - 节点管理系统

  - name: "嘎嘎机场"
    type: select
    use:
      - 嘎嘎机场

  - name: "马铃薯机场"
    type: select
    use:
      - 马铃薯机场

  - name: "年前机场"
    type: select
    use:
      - 年前机场

  - name: "三分机场"
    type: select
    use:
      - 三分机场

rules:
  # 常用服务
  - DOMAIN-SUFFIX,google.com,自动选择
  - DOMAIN-SUFFIX,youtube.com,自动选择
  - DOMAIN-SUFFIX,facebook.com,自动选择
  - DOMAIN-SUFFIX,twitter.com,自动选择
  - DOMAIN-SUFFIX,instagram.com,自动选择
  - DOMAIN-SUFFIX,whatsapp.com,自动选择
  - DOMAIN-SUFFIX,netflix.com,自动选择
  - DOMAIN-SUFFIX,spotify.com,自动选择
  - DOMAIN-SUFFIX,github.com,自动选择
  - DOMAIN-SUFFIX,wikipedia.org,自动选择

  # Telegram 相关
  - DOMAIN-SUFFIX,telegram.org,自动选择
  - DOMAIN-SUFFIX,t.me,自动选择
  - DOMAIN-SUFFIX,telegraph.com,自动选择
  - DOMAIN-SUFFIX,telegra.ph,自动选择

  # 其他常用服务
  - DOMAIN-SUFFIX,zoom.us,自动选择
  - DOMAIN-SUFFIX,slack.com,自动选择
  - DOMAIN-SUFFIX,discord.com,自动选择
  - DOMAIN-SUFFIX,twitch.tv,自动选择
  - DOMAIN-SUFFIX,reddit.com,自动选择

  # 国内应用直连
  - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,wechat.com,DIRECT
  - DOMAIN-SUFFIX,alipay.com,DIRECT

  # 广告屏蔽
  - DOMAIN-SUFFIX,adservice.google.com,REJECT
  - DOMAIN-SUFFIX,doubleclick.net,REJECT
  - DOMAIN-SUFFIX,googlesyndication.com,REJECT
  - DOMAIN-SUFFIX,google-analytics.com,REJECT

  # 默认规则
  - GEOIP,CN,DIRECT
  - MATCH,自动选择
    
